# Generated by Django 3.2.25 on 2024-07-10 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240710_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='required_grad_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grad_year',
            field=models.IntegerField(default=2027),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_organization_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='advisor_organization_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
