# Generated by Django 3.2.25 on 2024-07-10 18:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240710_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ical_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='grad_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('required', True), ('required_grad_year__isnull', True), ('type', 1)), models.Q(('required', False), ('required_grad_year__isnull', False), ('type', 2)), models.Q(('required', False), ('required_grad_year__isnull', True), ('type', 3)), _connector='OR'), name='core_organization_type'),
        ),
    ]
