# Generated by Django 3.2.25 on 2024-07-10 20:43

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240710_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.models.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
