# Generated by Django 3.2.25 on 2024-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_expopushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Student'), (2, 'Staff'), (3, 'Guest')], null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
