# Generated by Django 3.2.25 on 2024-07-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240711_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='ical_links',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='link',
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
