# Generated by Django 3.2.25 on 2024-07-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240711_1528'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='core_organization_type',
        ),
    ]
