# Generated by Django 3.2.25 on 2024-07-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_organization_core_organization_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('required', True), ('required_grad_year__isnull', True), ('type', 1)), models.Q(('required', False), ('required_grad_year__isnull', False), ('type', 2)), models.Q(('required', False), ('required_grad_year__isnull', True), ('type', 3)), _connector='OR'), name='core_organization_type'),
        ),
    ]
