# Generated by Django 3.2.25 on 2024-07-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_organization_core_organization_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='points',
        ),
        migrations.AddField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
